apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  labels:
    app.kubernetes.io/part-of: keycloak
spec:
  instances: 1
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
  storage:
    storageClass: local-path
    size: 1Gi
