apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-chart
  namespace: cnpg-system
  labels:
    app.kubernetes.io/part-of: cnpg-system
spec:
  interval: 1h
  url: https://cloudnative-pg.io/charts/
