apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cert-manager-admin-binding
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: cert-manager
  name: cluster-admin
